# Stage 1: build estático
FROM node:20-alpine AS build

RUN mkdir -p /app && chown node:node /app

WORKDIR /app

USER node

COPY --chown=node:node package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY --chown=node:node . .

ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Stage 2: runtime nginx
FROM nginx:alpine

# Ajusta permissões para o nginx rodar como não-root e instala curl para healthcheck
RUN apk update && apk add --no-cache curl && rm -rf /var/cache/apk/* && \
    chown -R nginx:nginx /var/cache/nginx /var/run /var/log/nginx && \
    chmod -R 777 /var/cache/nginx /var/run /var/log/nginx

RUN rm /etc/nginx/conf.d/default.conf

# Apenas os arquivos HTML/JS podem pertencer ao Nginx agora
COPY --from=build --chown=nginx:nginx /app/dist /usr/share/nginx/html
COPY --chown=nginx:nginx nginx.prod.conf /etc/nginx/conf.d/default.conf

USER nginx

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
